#                                 
format = """
[](fg:#242438 bg:#242438)\
[󰣇](fg:#2F71DA bg:#242438)\
[  ](fg:#242438 bg:#242438)\
$username\
[](fg:#242438 bg:#00FFFF)\
$directory\
[](fg:#00FFFF bg:#242438)\
$git_branch\
$git_status\
[](fg:#242438 bg:#00ffff)\
[ ](fg:#00ffff)\
"""

right_format = """
[](fg:#00ffff)\
[](fg:#242438 bg:#00ffff)\
$time\
$all
$character
"""

[username]
show_always = true
style_user = "fg:#F6F5F4 bg:#242438"
style_root = "fg:#F6F5F4 bg:#242438"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#242438 bg:#00FFFF"
format = "[ $path ]($style)"
disabled = false

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#F6F5F4 bg:#242438"
format = '[ $symbol $branch ]($style)'
disabled = false

[git_status]
style = "fg:#F6F5F4 bg:#242438"
format = '[$all_status$ahead_behind ]($style)'
disabled = false

# Start languages and tools #

[c]
symbol = ""
style = "fg:#00FFFF bg:#840a2c"
format = '[ $symbol ($version) ]($style)'
disabled = false

[kubernetes]
style = "fg:#00FFFF bg:#326ce5"
format = '[ on ﴱ ($user on )($cluster in )$context \($namespace\) ]($style)'
disabled = false

[gcloud]
symbol = " "
style = "fg:#00FFFF bg:#0f9d58"
format = '[ on $symbol $account(@$domain)(\($region\)) ]($style) '
# format = '[ on $symbol account@company.iam.gserviceaccount.com(\($region\)) ]($style) ' # for testing purposes
disabled = false

[golang]
symbol = ""
style = "fg:#00FFFF bg:#007d9c"
format = '[ $symbol ($version) ]($style)'
disabled = false

[java]
symbol = ""
style = "fg:#00FFFF bg:#007396"
format = '[ $symbol ($version) ]($style)'
disabled = false

[lua]
symbol = ""
style = "fg:#00FFFF bg:#000080"
format = '[ $symbol ($version) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:#00FFFF bg:#5fa04e"
format = '[ $symbol ($version) ]($style)'
disabled = false

[package]
symbol = ""
style = "fg:#00FFFF bg:#cb3837"
format = '[ $symbol ($version) ]($style)'
disabled = false

[php]
symbol = ''
style = "fg:#00ffff bg:#4F5B93"
format = '[ $symbol ($version) ]($style)'
disabled = false

[python]
symbol = ''
style = "fg:$00ffff bg:#ffdf76"
format = '[ $symbol ($version) ]($style)'
disabled = false

[rust]
symbol = ""
style = "fg:#00ffff bg:#a72145"
format = '[ $symbol ($version) ]($style)'
disabled = false

# End languages and tools #

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#00ffff bg:#242438"
format = '[  $time ]($style)'

[cmd_duration]
style = "fg:#000000 bg:yellow"
format = "[ took $duration ]($style)"

[character]
format = " $symbol"
